apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-sriov-demo
spec:
  running: true
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 128Mi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          interfaces:
          - name: sriov-net
            sriov: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
